#!/bin/bash

# Runs the B-12-like analysis on the high-purity sample, giving its
# results. Runs it for the anti-high-purity sample, and uses the ratio
# to give the number of captures in the loose sample.

out=carbondenominators_finalfit.out

set -o pipefail

if ! root -b -q carbondenominators_finalfit.C+ | tee /tmp/$$.$out; then
  exit 1
fi

mv -f /tmp/$$.$out $out

printf '/* Automatically generated by carbondenominators_finalfit.C */\n' \
  > carbondenominators_finalfit_out.h
grep '^const ' $out >> carbondenominators_finalfit_out.h

grep TECHNOTE $out > carbondenominators_finalfit_out.technote
