#!/bin/bash

out=dcfluids_finalfit.out
set -o pipefail

if ! root -b -q dcfluids_finalfit.C | tee /tmp/$$.$out; then
  exit 1
fi

mv -f /tmp/$$.$out $out

printf '/* Automatically generated by dcfluids_finalfit.C */\n' \
  > dcfluids_finalfit_out.h
grep '^const ' $out >> dcfluids_finalfit_out.h

grep TECHNOTE $out > dcfluids_finalfit_out.technote
