#!/bin/bash

out=b12gamma_finalfit.out 
set -o pipefail

if ! root -b -q b12gammafinalfit.C+'(0)' | tee /tmp/$$.$out || 
   ! root -b -q b12gammafinalfit.C+'(1)' | tee -a /tmp/$$.$out; then
  exit 1
fi

mv -f /tmp/$$.$out $out

printf '/* Automatically generated by b12gammafinalfit.C */\n' \
  > b12gamma_finalfit_out.h

grep TECHNOTE $out > b12gamma_finalfit_out.technote
