#!/bin/bash

out=li8_finalfit.out 
set -o pipefail

if ! root -b -q li8finalfit.C+O | tee /tmp/$$.$out; then
  mv -f /tmp/$$.$out $out.fail
  exit 1
fi

mv -f /tmp/$$.$out $out

printf '/* Automatically generated by li8finalfit.C */\n' \
  > li8_finalfit_out.h
grep '^const ' $out >> li8_finalfit_out.h

grep TECHNOTE $out > li8_finalfit_out.technote
