#!/bin/bash

out=noncarbondenominators_finalfit.out
set -o pipefail

if ! root -b -q noncarbondenominators_finalfit.C | tee /tmp/$$.$out; then
  mv -f /tmp/$$.$out $out.fail
  exit 1
fi

mv -f /tmp/$$.$out $out

printf '/* Automatically generated by noncarbondenominators_finalfit.C */\n' \
  > noncarbondenominators_finalfit_out.h
grep '^const ' $out >> noncarbondenominators_finalfit_out.h

grep TECHNOTE $out > noncarbondenominators_finalfit_out.technote
