#!/bin/bash

root -b -q dcfluids_finalfit.C | tee dcfluids_finalfit.out

printf '/* Automatically generated by dcfluids_finalfit.C */\n' \
  > dcfluids_finalfit_out.h
grep '^const ' dcfluids_finalfit.out >> dcfluids_finalfit_out.h

grep TECHNOTE dcfluids_finalfit.out > dcfluids_finalfit_out.technote
