#!/bin/bash

# Runs the B-12-like analysis on the high-purity sample, giving its
# results. Runs it for the anti-high-purity sample, and uses the ratio
# to give the number of captures in the loose sample. Sends output for
# tech note to loosecaptures_finalfit.out and to be used downstream to
# loosecaptures_finalfit_out.h

out=loosecaptures_finalfit.out

set -o pipefail

if ! root -b -q loosecaptures_finalfit.C+ | tee /tmp/$$.$out; then
  exit 1
fi

mv -f /tmp/$$.$out $out

printf '/* Automatically generated by loosecaptures_finalfit.C */\n' \
  > loosecaptures_finalfit_out.h
grep '^const ' $out >> loosecaptures_finalfit_out.h

grep TECHNOTE $out > loosecaptures_finalfit_out.technote
