#!/bin/bash

out=b12gamma_finalfit.out 
set -o pipefail

if ! root -b -q b12gammafinalfit.C+O'(0)' | tee /tmp/$$.$out || 
   ! root -b -q b12gammafinalfit.C+O'(1)' | tee -a /tmp/$$.$out; then
  mv -f /tmp/$$.$out $out.fail
  exit 1
fi

mv -f /tmp/$$.$out $out

printf '/* Automatically generated by b12gammafinalfit.C */\n' \
  > b12gamma_finalfit_out.h
grep '^const ' $out >> b12gamma_finalfit_out.h

grep TECHNOTE $out > b12gamma_finalfit_out.technote
